# Generated by Django 4.0.5 on 2022-06-21 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('amount', models.PositiveSmallIntegerField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='uploads/')),
                ('is_active', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(to='app1.category')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_shop', to='app1.shop')),
            ],
        ),
    ]
